---
- name: set fact - records_dir
  set_fact:
    records_dir: "{{ git_path }}/records"

- name: remove records dir if it already exists
  file: state=absent
        path={{ records_dir }}

- name: create records dir
  file: state=directory
        path={{ records_dir }}

- name: copy config_records
  template: src=config_records.j2
            dest={{ records_dir }}/config_records
            backup=no

- name: copy commit_list
  template: src=commit_list.j2
            dest={{ records_dir }}/commit_list
            backup=no
